### ISSUE TITLE
[BUG] Unable to build ags

### ISSUE THREAD

**Issue by t0m5k1** [mylinuxforwork/dotfiles#238]
**Describe the bug**
attempting to install with yay on Arch results in a build error with aylurs-gtk-shell

**To Reproduce**
yay -S ml4w-hyprland
See error

**Expected behavior**
Your dotfiles be installed with no errors.

Here is the full terminal output:

```
AUR Explicit (1): ml4w-hyprland-2.9.6.1-1
AUR Dependency (1): aylurs-gtk-shell-1.8.2-3
Sync Make Dependency (3): typescript-5.5.4-1, glib2-devel-2.80.5-1, npm-10.8.3-1
:: PKGBUILD up to date, skipping download: ml4w-hyprland
:: PKGBUILD up to date, skipping download: aylurs-gtk-shell
  2 ml4w-hyprland                    (Build Files Exist)
  1 aylurs-gtk-shell                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/2): /home/t0m5k1/.cache/yay/ml4w-hyprland
HEAD is now at e144e54 Version 2.9.6.1
Removing ml4w-hyprland
Removing src/
:: Deleting (2/2): /home/t0m5k1/.cache/yay/aylurs-gtk-shell
HEAD is now at 2ab04a8 Initial upload: libastal-network-git r1.7662145-1
warning: could not open directory 'pkg/': Permission denied
Removing aylurs-gtk-shell-1.8.2.tar.gz
Removing pkg/
Skipping repository src/ags
Removing src/aylurs-gtk-shell-1.8.2.tar.gz
==> Making package: ml4w-hyprland 2.9.6.1-1 (Tue 10 Sep 2024 18:07:40 BST)
==> Retrieving sources...
  -> Downloading ml4w-hyprland...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 48.2M    0 48.2M    0     0  5327k      0 --:--:--  0:00:09 --:--:-- 6113k
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
    ml4w-hyprland ... Skipped
==> Making package: aylurs-gtk-shell 1.8.2-3 (Tue 10 Sep 2024 18:07:50 BST)
==> Retrieving sources...
  -> Downloading aylurs-gtk-shell-1.8.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  425k  100  425k    0     0   768k      0 --:--:-- --:--:-- --:--:--  768k
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    aylurs-gtk-shell-1.8.2.tar.gz ... Passed
:: (1/2) Parsing SRCINFO: ml4w-hyprland
:: (2/2) Parsing SRCINFO: aylurs-gtk-shell
[sudo] password for t0m5k1: 
resolving dependencies...
looking for conflicting packages...

Packages (8) libngtcp2-1.7.0-1  node-gyp-10.2.0-1  nodejs-22.8.0-1  nodejs-nopt-7.2.0-2  semver-7.6.3-1  glib2-devel-2.80.5-1  npm-10.8.3-1  typescript-5.5.4-1

Total Installed Size:  96.13 MiB

:: Proceed with installation? [Y/n] 
(8/8) checking keys in keyring                                                                                           [########################################################################] 100%
(8/8) checking package integrity                                                                                         [########################################################################] 100%
(8/8) loading package files                                                                                              [########################################################################] 100%
(8/8) checking for file conflicts                                                                                        [########################################################################] 100%
(8/8) checking available disk space                                                                                      [########################################################################] 100%
:: Processing package changes...
(1/8) installing libngtcp2                                                                                               [########################################################################] 100%
(2/8) installing nodejs                                                                                                  [########################################################################] 100%
Optional dependencies for nodejs
    npm: nodejs package manager [pending]
(3/8) installing typescript                                                                                              [########################################################################] 100%
(4/8) installing glib2-devel                                                                                             [########################################################################] 100%
(5/8) installing nodejs-nopt                                                                                             [########################################################################] 100%
(6/8) installing semver                                                                                                  [########################################################################] 100%
(7/8) installing node-gyp                                                                                                [########################################################################] 100%
Optional dependencies for node-gyp
    gcc: to build C++ modules [installed]
    make: to build C++ modules [installed]
    python: to build C++ modules [installed]
(8/8) installing npm                                                                                                     [########################################################################] 100%
Optional dependencies for npm
    git: for dependencies using Git URL's [installed]
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Refreshing PackageKit...
(3/3) Refreshing py3status arch_updates module...
==> Making package: aylurs-gtk-shell 1.8.2-3 (Tue 10 Sep 2024 18:07:59 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found aylurs-gtk-shell-1.8.2.tar.gz
==> Validating source files with sha256sums...
    aylurs-gtk-shell-1.8.2.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting aylurs-gtk-shell-1.8.2.tar.gz with bsdtar
==> Sources are ready.
==> Making package: aylurs-gtk-shell 1.8.2-3 (Tue 10 Sep 2024 18:08:00 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
/usr/lib/node_modules/npm/lib/cli/validate-engines.js:31
    throw err
    ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/classes/range.js:188:15)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/functions/satisfies.js:1:15)

Node.js v22.8.0
==> ERROR: A failure occurred in build().
    Aborting...
 -> Failed to install layer, rolling up to next layer.error:error making: aylurs-gtk-shell - exit status 4
==> Making package: aylurs-gtk-shell 1.8.2-3 (Tue 10 Sep 2024 18:08:00 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found aylurs-gtk-shell-1.8.2.tar.gz
==> Validating source files with sha256sums...
    aylurs-gtk-shell-1.8.2.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting aylurs-gtk-shell-1.8.2.tar.gz with bsdtar
==> Sources are ready.
==> Making package: aylurs-gtk-shell 1.8.2-3 (Tue 10 Sep 2024 18:08:01 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
/usr/lib/node_modules/npm/lib/cli/validate-engines.js:31
    throw err
    ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/classes/range.js:188:15)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/functions/satisfies.js:1:15)

Node.js v22.8.0
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: aylurs-gtk-shell-exit status 4
==> Making package: ml4w-hyprland 2.9.6.1-1 (Tue 10 Sep 2024 18:08:02 BST)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> aylurs-gtk-shell
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
 -> error making: ml4w-hyprland-exit status 8
checking dependencies...
:: glib2 optionally requires glib2-devel: development tools

Packages (8) libngtcp2-1.7.0-1  node-gyp-10.2.0-1  nodejs-22.8.0-1  nodejs-nopt-7.2.0-2  semver-7.6.3-1  glib2-devel-2.80.5-1  npm-10.8.3-1  typescript-5.5.4-1

Total Removed Size:  96.13 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/8) removing npm                                                                                                       [########################################################################] 100%
(2/8) removing node-gyp                                                                                                  [########################################################################] 100%
(3/8) removing semver                                                                                                    [########################################################################] 100%
(4/8) removing nodejs-nopt                                                                                               [########################################################################] 100%
(5/8) removing glib2-devel                                                                                               [########################################################################] 100%
(6/8) removing typescript                                                                                                [########################################################################] 100%
(7/8) removing nodejs                                                                                                    [########################################################################] 100%
(8/8) removing libngtcp2                                                                                                 [########################################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Refreshing PackageKit...
(3/3) Refreshing py3status arch_updates module...
 -> Failed to install the following packages. Manual intervention is required:
aylurs-gtk-shell - exit status 4
ml4w-hyprland - exit status 8
```

**Comment by mylinuxforwork** [comment]
Please run

sudo pacman -Syu

and try again.

**Comment by t0m5k1** [comment]
I did that before I started .

**Comment by mylinuxforwork** [comment]
Can you try to install ags manually

yay -S aylurs-gtk-shell # or aylurs-gtk-shell-git

**Comment by t0m5k1** [comment]
get exactly the same result:


```
AUR Explicit (1): aylurs-gtk-shell-1.8.2-3
Sync Make Dependency (3): typescript-5.5.4-1, glib2-devel-2.80.5-1, npm-10.8.3-1
:: PKGBUILD up to date, skipping download: aylurs-gtk-shell
  1 aylurs-gtk-shell                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: aylurs-gtk-shell 1.8.2-3 (Wed 11 Sep 2024 21:23:25 BST)
==> Retrieving sources...
  -> Found aylurs-gtk-shell-1.8.2.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    aylurs-gtk-shell-1.8.2.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: aylurs-gtk-shell
[sudo] password for t0m5k1: 
resolving dependencies...
looking for conflicting packages...

Packages (8) libngtcp2-1.7.0-1  node-gyp-10.2.0-1  nodejs-22.8.0-1  nodejs-nopt-7.2.0-2  semver-7.6.3-1  glib2-devel-2.80.5-1  npm-10.8.3-1  typescript-5.5.4-1

Total Installed Size:  96.13 MiB

:: Proceed with installation? [Y/n] 
(8/8) checking keys in keyring                                                                                           [########################################################################] 100%
(8/8) checking package integrity                                                                                         [########################################################################] 100%
(8/8) loading package files                                                                                              [########################################################################] 100%
(8/8) checking for file conflicts                                                                                        [########################################################################] 100%
(8/8) checking available disk space                                                                                      [########################################################################] 100%
:: Processing package changes...
(1/8) installing libngtcp2                                                                                               [########################################################################] 100%
(2/8) installing nodejs                                                                                                  [########################################################################] 100%
Optional dependencies for nodejs
    npm: nodejs package manager [pending]
(3/8) installing nodejs-nopt                                                                                             [########################################################################] 100%
(4/8) installing semver                                                                                                  [########################################################################] 100%
(5/8) installing node-gyp                                                                                                [########################################################################] 100%
Optional dependencies for node-gyp
    gcc: to build C++ modules [installed]
    make: to build C++ modules [installed]
    python: to build C++ modules [installed]
(6/8) installing npm                                                                                                     [########################################################################] 100%
Optional dependencies for npm
    git: for dependencies using Git URL's [installed]
(7/8) installing typescript                                                                                              [########################################################################] 100%
(8/8) installing glib2-devel                                                                                             [########################################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Refreshing PackageKit...
(3/3) Refreshing py3status arch_updates module...
==> Making package: aylurs-gtk-shell 1.8.2-3 (Wed 11 Sep 2024 21:23:32 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found aylurs-gtk-shell-1.8.2.tar.gz
==> Validating source files with sha256sums...
    aylurs-gtk-shell-1.8.2.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting aylurs-gtk-shell-1.8.2.tar.gz with bsdtar
==> Sources are ready.
==> Making package: aylurs-gtk-shell 1.8.2-3 (Wed 11 Sep 2024 21:23:33 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
/usr/lib/node_modules/npm/lib/cli/validate-engines.js:31
    throw err
    ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/classes/range.js:188:15)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/functions/satisfies.js:1:15)

Node.js v22.8.0
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: aylurs-gtk-shell-exit status 4
checking dependencies...
:: glib2 optionally requires glib2-devel: development tools

Packages (8) libngtcp2-1.7.0-1  node-gyp-10.2.0-1  nodejs-22.8.0-1  nodejs-nopt-7.2.0-2  semver-7.6.3-1  glib2-devel-2.80.5-1  npm-10.8.3-1  typescript-5.5.4-1

Total Removed Size:  96.13 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/8) removing npm                                                                                                       [########################################################################] 100%
(2/8) removing node-gyp                                                                                                  [########################################################################] 100%
(3/8) removing semver                                                                                                    [########################################################################] 100%
(4/8) removing nodejs-nopt                                                                                               [########################################################################] 100%
(5/8) removing glib2-devel                                                                                               [########################################################################] 100%
(6/8) removing typescript                                                                                                [########################################################################] 100%
(7/8) removing nodejs                                                                                                    [########################################################################] 100%
(8/8) removing libngtcp2                                                                                                 [########################################################################] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Refreshing PackageKit...
(3/3) Refreshing py3status arch_updates module...
 -> Failed to install the following packages. Manual intervention is required:
aylurs-gtk-shell - exit status 4
```

**Comment by mylinuxforwork** [comment]
It seams there is an issue with ags.

Can you try to cleanbuild?

Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)

Select A for cleanbuild and try again.

**Comment by mylinuxforwork** [comment]
@t0m5k1 what is your distro?

**Comment by t0m5k1** [comment]
ARCH

**Comment by mylinuxforwork** [comment]
Cannot confirm this issue in my latest tests. Can you try again with yay -S ml4w-hyprland-git Or soon with the new 2.9.6.2
