### ISSUE TITLE
[BUG] After update to 2.9.7.1 many modules doesn't work (waybar, hyprshade, waypaper)

### ISSUE THREAD

**Issue by Fedex159** [mylinuxforwork/dotfiles#541]
**Describe the bug**
After update from 2.9.7.0 to 2.9.7.1 some modules are not working anymore.
- Waybar won't autostart
- Waypaper error module in terminal
- Hyprshade script error module in terminal

**To Reproduce**
1. Go to dotfiles/.config/scripts/
2. Execute hyrpshade.sh
3. See error in terminal (similar error with waypaper)

Error
```
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
:: hyprshade is not running
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
:: hyprshade started with 
```

**Expected behavior**
- Waybar should auto start if is enable
- Hyprshade should be enable when toggle is true or the script is execute
- Should see the wallpaper in my desktop

**Screenshots**

![imagen](https://github.com/user-attachments/assets/c9eab5ac-5eea-4b9e-a3b8-1212fa55c48f)

![imagen](https://github.com/user-attachments/assets/edfee188-ca9b-45a0-9369-4b08dfe1a6d4)

![imagen](https://github.com/user-attachments/assets/8255206d-1856-45c2-8948-eeff4b776681)

**Distribution (please complete the following information):**
 - Arch Linux 6.12.6-arch1-1
 - Nvidia

**Comment by Fedex159** [comment]
Rebuilding some aur packages and installing new dependencies seems fix the issue with waybar, hyprshade and hyprlock

**Comment by saipr0** [comment]
Hey, I am facing the same issue. how did you fix it? Also is waypaper still broken then?

**Comment by cap0bvious** [comment]
> Rebuilding some aur packages and installing new dependencies seems fix the issue
Could you tell more about that? I have the same issue

**Comment by nxtkofi** [comment]
> Rebuilding some aur packages and installing new dependencies seems fix the issue with waybar, hyprshade and hyprlock

Also asking for elaboration on what are 'some aur packages' and how exactly did You install new dependencies?
TIA

**Comment by Fedex159** [comment]
> > Rebuilding some aur packages and installing new dependencies seems fix the issue
> 
> Could you tell more about that? I have the same issue

Sure, I tried differents commands, but these are the ones that worked for me.

Run this command `pacman -Qoq /usr/lib/python3.13` to get a list of packages that depends of python ([source](https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/)). Change python version if you don't have 3.13 installed.

Then, what I did was to use the output of the list to rebuild all packages using `paru` instead of `pacman` with this command:
```
paru -S $(paru -Qoq /usr/lib/python3.13) --rebuild
```

After that, you can logout and login again, try to run `hyprshade` or `waypaper` to see if there some errors yet.

In my casa, I had to install a new dependency `python-screeninfo`. I did that with this command: `paru -S python-screeninfo --rebuild` (maybe the rebuild flag is not necessary but II added it anyway).

After that, waypaper, hyprshade and waybar start working without any change.

I hope this work for you.

**Comment by Fedex159** [comment]
> > Rebuilding some aur packages and installing new dependencies seems fix the issue with waybar, hyprshade and hyprlock
> 
> Also asking for elaboration on what are 'some aur packages' and how exactly did You install new dependencies? TIA

[Here](https://github.com/mylinuxforwork/dotfiles/issues/541#issuecomment-2558541783) the steps I did. About  'some aur packages', is because I rebuilt only packages that depents of python only, not all aur packages that I have installed.

**Comment by nxtkofi** [comment]
I managed to make it work by doing so on Arch Linux, AMD GPU:
```
sudo pacman -Syu
yay -S waypaper
yay -S python-screeninfo
```

**Comment by cap0bvious** [comment]
I tried both variants and waypaper still crashes trying to run:
```
/home/capobvious : waypaper
Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'
```

**Comment by Fedex159** [comment]
> I tried both variants and waypaper still crashes trying to run:
> 
> ```
> /home/capobvious : waypaper
> Traceback (most recent call last):
>   File "/usr/bin/waypaper", line 5, in <module>
>     from waypaper.__main__ import run
>   File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
>     from waypaper.app import App
>   File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
>     import imageio
> ModuleNotFoundError: No module named 'imageio'
> ```

Try rebuild only that package like this `paru -S python-imageio --rebuild`

**Comment by cap0bvious** [comment]
That made waypaper run with no issues, thanks!
It seems that the reason for the issue isn't ml4w, but python 3.13 that just got released

**Comment by Fedex159** [comment]
> That made waypaper run with no issues, thanks! It seems that the reason for the issue isn't ml4w, but python 3.13 that just got released

Yeah, great that works.

**Comment by degobbis** [comment]
Unfortunately, it doesn't solve the problem for me. Do you have any other ideas?

**Comment by daveleslie** [comment]
got it working with
```bash
sudo pacman -Syu
yay -S waypaper
yay -S python-screeninfo
yay -S python-imageio
```

**Comment by degobbis** [comment]
> got it working with
> 
> ```shell
> sudo pacman -Syu
> yay -S waypaper
> yay -S python-screeninfo
> yay -S python-imageio
> ```

Unfortunately, it doesn't solve the problem for me either. 
I noticed that `yay -S waypaper` still installs `waypaper-git`, can anyone confirm this?

**Comment by Fedex159** [comment]
> > got it working with
> > ```shell
> > sudo pacman -Syu
> > yay -S waypaper
> > yay -S python-screeninfo
> > yay -S python-imageio
> > ```
> 
> Unfortunately, it doesn't solve the problem for me either. I noticed that `yay -S waypaper` still installs `waypaper-git`, can anyone confirm this?

What error are you getting when run waypaper in the terminal?

**Comment by NuLLxD** [comment]
`Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
ModuleNotFoundError: No module named 'waypaper'`

`Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'`

Unfortunately none of these commands work for me either. I've even done a clean install of the dotfiles and all packages.

**Comment by degobbis** [comment]
I could now downgrade waypaper back to the normal version, the error is in the terminal:
```
$ waypaper --restore
Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'
```

**Comment by degobbis** [comment]
These Packages are installed and reinstalled
```
$ pacman -Q | grep imageio                             
python-imageio 2.36.1-2
python-imageio-ffmpeg 0.5.1-2
```

**Comment by Fedex159** [comment]
> `Traceback (most recent call last): File "/usr/bin/waypaper", line 5, in <module> from waypaper.__main__ import run ModuleNotFoundError: No module named 'waypaper'`
> 
> `Traceback (most recent call last): File "/usr/bin/hyprshade", line 5, in <module> from hyprshade.cli import main ModuleNotFoundError: No module named 'hyprshade'`
> 
> Unfortunately none of these seem to be a solution. I've even done a clean install of the dotfiles and all packages.

Try this:
```
paru -S waypaper hyprshade --rebuild
```

Then, if you run  waypaper in terminal, check if the error change.

**Comment by Fedex159** [comment]
> I could now downgrade waypaper back to the normal version, the error is in the terminal:
> 
> ```
> $ waypaper --restore
> Traceback (most recent call last):
>   File "/usr/bin/waypaper", line 5, in <module>
>     from waypaper.__main__ import run
>   File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
>     from waypaper.app import App
>   File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
>     import imageio
> ModuleNotFoundError: No module named 'imageio'
> ```

Try [this](https://github.com/mylinuxforwork/dotfiles/issues/541#issuecomment-2558547970)

**Comment by degobbis** [comment]
Problem found:
Python has been updated to version 3.13, but the additional packages are in the path for Python 3.12. Therefore it cannot find the packages.

I think a downgrade could solve the problem.

**Comment by degobbis** [comment]
Downgrading the Python version was not the solution.
I found a temporary solution, I added the following line in my custom.conf:
`env = PYTHONPATH,/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH`

Also added this in my ZSH custom init file:
`export PYTHONPATH=/usr/lib/python3.12/site-packages:/usr/lib/python3.13/site-packages:$PYTHONPATH`

**Comment by NuLLxD** [comment]
> > `Traceback (most recent call last): File "/usr/bin/waypaper", line 5, in <module> from waypaper.__main__ import run ModuleNotFoundError: No module named 'waypaper'`
> > `Traceback (most recent call last): File "/usr/bin/hyprshade", line 5, in <module> from hyprshade.cli import main ModuleNotFoundError: No module named 'hyprshade'`
> > Unfortunately none of these seem to be a solution. I've even done a clean install of the dotfiles and all packages.
> 
> Try this:
> 
> ```
> paru -S waypaper hyprshade --rebuild
> ```
> 
> Then, if you run waypaper in terminal, check if the error change.

This fixed it, thank you. I also had to rebuild some other packages as well. 

```
paru -S python-screeninfo --rebuild
```

To summarize for everyone else who may be looking for a solution, try this;

```
paru -S waypaper hyprshade python-imageio python-screeninfo --rebuild
```

**Comment by degobbis** [comment]
I did that, but it didn't solve the problem.

**Comment by NuLLxD** [comment]
> I did that, but it didn't solve the problem.

I would recommend uninstalling your dotfiles, in the case of yay 
```
yay -R ml4w-hyprland
```
or in the case of paru
```
paru -R ml4w-hyprland
```
Then install the new dotfiles via your package manager and use the setup script to retain any custom configuration settings you may have. 
```
ml4w-hyprland-setup
```
This is what I did previous to the steps in my last reply.

**Comment by Tony15246** [comment]
> > I tried both variants and waypaper still crashes trying to run:
> > ```
> > /home/capobvious : waypaper
> > Traceback (most recent call last):
> >   File "/usr/bin/waypaper", line 5, in <module>
> >     from waypaper.__main__ import run
> >   File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
> >     from waypaper.app import App
> >   File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
> >     import imageio
> > ModuleNotFoundError: No module named 'imageio'
> > ```
> 
> Try rebuild only that package like this `paru -S python-imageio --rebuild`

works like a charm, fixed my problem, thank you

**Comment by degobbis** [comment]
I forgot to restart... :D
Now everything works fine, even without setting the variable.
Thx.

**Comment by colts45s** [comment]
> > `Traceback (most recent call last): File "/usr/bin/waypaper", line 5, in <module> from waypaper.__main__ import run ModuleNotFoundError: No module named 'waypaper'`
> > `Traceback (most recent call last): File "/usr/bin/hyprshade", line 5, in <module> from hyprshade.cli import main ModuleNotFoundError: No module named 'hyprshade'`
> > Unfortunately none of these seem to be a solution. I've even done a clean install of the dotfiles and all packages.
> 
> Try this:
> 
> ```
> paru -S waypaper hyprshade --rebuild
> ```
> 
> Then, if you run waypaper in terminal, check if the error change.

 Rebuilding the packages mentioned above solved this for me as well. Started with waypaper then kept going until running waypaper worked. Thanks
