### ISSUE TITLE
[BUG]`hyprshade.sh` not working on new update

### ISSUE THREAD

**Issue by mrjxtr** [mylinuxforwork/dotfiles#581]
**Describe the bug**
When trying to toggle `Hyprshade` by clicking the icon on `Waybar`.

**To Reproduce**
1. update to latest ml4w with `ml4w-hyprland-setup`

**Expected behavior**
Clicking the toggle will activate `Hyprshad`

**Screenshots**
Will only show this message but does nothing.
![image](https://github.com/user-attachments/assets/ad7da5d5-5f9c-4cb4-9232-c865ff868646)

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**

```
❯ ls
 cleanup.sh                 keybindings.sh         toggleallfloat.sh
 disabledm.sh               loadconfig.sh          wallpaper-automation.sh
 gamemode.sh                moveTo.sh              wallpaper-cache.sh
 gtk.sh                     power.sh               wallpaper-effects.sh
 hypridle.sh                restart-hypridle.sh    wallpaper-restore.sh
 hyprshade.sh               screenshot.sh          wallpaper.sh
 init-wallpaper-engine.sh   toggle-animations.sh   xdg.sh

    ~/dotfiles/.config/hypr/scripts                                                   
❮ ./hyprshade.sh
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
:: hyprshade is not running
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'
:: hyprshade started with 

    ~/dotfiles/.config/hypr/scripts                                                   
❮ hyprshade
Traceback (most recent call last):
  File "/usr/bin/hyprshade", line 5, in <module>
    from hyprshade.cli import main
ModuleNotFoundError: No module named 'hyprshade'

    ~/dotfiles/.config/hypr/scripts                                                   
❮ whereis hyprshade
hyprshade: /usr/bin/hyprshade /usr/share/hyprshade
```

**Comment by degobbis** [comment]
Your Python libraries are probably not fully available for the new version.
If the path still exists `/usr/lib/python3.13/site-packages/`, then the packages it contains have not yet been transferred.
You can try this: `yay -S $(yay -Qoq /usr/lib/python3.12) --rebuild` and then **reboot the system**.

If everything worked, the path to python3.12 will no longer exist after the reboot and hyprshade should work again.

**Comment by mrjxtr** [comment]
> Your Python libraries are probably not fully available for the new version. If the path still exists `/usr/lib/python3.13/site-packages/`, then the packages it contains have not yet been transferred. You can try this: `yay -S $(yay -Qoq /usr/lib/python3.12) --rebuild` and then **reboot the system**.
> 
> If everything worked, the path to python3.12 will no longer exist after the reboot and hyprshade should work again.

Thank! this worked perfectly.
